# jekyll config file
#

exclude: ["README.md"]
permalink: /:year/:month/:day/:title
production_url : http://mrphilroth.com

title : phil roth
author :
  name : Phil Roth
  email : mr.phil.roth@gmail.com
  github : mrphilroth
  twitter : mrphilroth
